declare var String: { toLocaleString: (param: any) => void; };

export function deflectionInitStrings() {
    String.toLocaleString({
        'en': {
            'autoFocus': 'Auto focus',
            'autoFocus_description': 'Specifies whether the Querybox gets the focus and is selected on initialization. ',
            'enableQuerySyntax': 'Enable query syntax',
            'enableQuerySyntax_description': 'Specifies whether the Coveo Platform does not try to interpret special query syntax such as field references in the query entered through the query box. ',
            'enableLowercaseOperators': 'Enable lowercase operators',
            'enableLowercaseOperators_description': 'Specifies whether to also interpret lowercase keywords (like: or }, and) as operators. When false }, only uppercase keywords (Or }, AND) are recognized as operators. ',
            'enablePartialMatch': 'Enable partial match',
            'enablePartialMatch_description': 'Specifies whether a query containing a large number of keywords is automatically converted to a partial match expression to only match documents containing a subset of the keywords. ',
            'enableQuestionMarks': 'Enable question marks',
            'enableQuestionMarks_description': 'Specifies whether a question mark character (?) in a query is interpreted as a wildcard. ',
            'enableSearchAsYouType': 'Enable search-as-you-type',
            'enableSearchAsYouType_description': 'Specifies whether a new query is automatically triggered whenever the user types in new text inside the query box. ',
            'enableWildcards': 'Enable wildcards',
            'enableWildcards_description': 'Specifies whether the Coveo Platform expands keywords containing wildcard characters to the possible matching keywords to broaden the query. ',
            'partialMatchKeywords': 'Partial match keywords',
            'partialMatchKeywords_description': 'When partial match is enabled }, this option specifies the minimum number of keywords that must be present in the query for to activate partial match. ',
            'partialMatchThreshold': 'Partial match threshold',
            'partialMatchThreshold_description': 'Specifies the minimum number of keywords that a document must contain to be included in search results.',
            'searchAsYouTypeDelay': 'Search-as-you-type delay',
            'searchAsYouTypeDelay_description': 'When search-as-you-type is enabled }, specifies the delay in milliseconds before a new query is triggered when the user types in new text inside the query box. ',
            'enableQueryExtensionAddon': 'Enable query extension add-on',
            'enableRevealQuerySuggestAddon': 'Enable reveal query suggest add-on',
            'enableFieldAddon': 'Enable field add-on',
            'enableSimpleFieldAddon': 'Enable simple field add-on',
            'SearchboxAdvancedSettings': 'Searchbox Advanced Settings',
            'StartTypingCaseForSuggestions': 'Describe your problem to see possible solutions',
            'Field_description': 'This component creates an input element in a case form.',
            'Picklist_description': 'This component creates a picklist element in a case form.',
            'Submit_description': 'This component creates a submit button in a case form.',
            'Cancel_description': 'This component creates a cancel button in a case form.',
            'Text_description': 'This component adds text.',
            'CaseCreationEditHeader': 'Form',
            'CaseCreation_searchDelay': 'Delay',
            'CaseCreation_searchDelay_description': 'Specifies the delay in milliseconds before a new query is triggered when the end-user types new text inside a Field component.',
            'CaseCreation_searchType': 'Type',
            'CaseCreation_searchType_description': 'Specifies that only results of the specified type are returned.',
            'CaseCreation_searchSort': 'Sort',
            'CaseCreation_searchSort_description': 'Specifies how to sort the results.',
            'CaseCreation_useSomeOnAllKeywords': 'Use some of the keywords.',
            'CaseCreation_useSomeOnAllKeywords_description': 'Specifies whether to add a $some query extension containing the search keywords of the form. The search keywords are those from Field and Picklist components where enableSearch is set to true.',
            'CaseCreation_someBest': 'Extract this number of best keywords',
            'CaseCreation_someBest_description': 'Specifies the X best keywords that are to be matched.',
            'CaseCreation_someMatch': 'Documents should match this number of extracted keywords',
            'CaseCreation_someMatch_description': 'Specifies that only documents containing X or more keywords of those provided are to be matched.',
            'CaseCreation_someRemoveStopWords': 'Remove stop words',
            'CaseCreation_someRemoveStopWords_description': 'Specifies whether to remove any stop word present in the keywords.',
            'CaseCreation_someMaximum': 'Maximum number of keywords to match',
            'CaseCreation_someMaximum_description': 'Specifies the maximum number of keywords to use. If a larger number of keywords is provided, some keywords are completely ignored.',
            'CaseCreation_useDefaultRule': 'Use default assignment rules',
            'CaseCreation_useDefaultRule_description': 'Specifies if we want the default case assignment rules to be used.',
            'CaseCreation_openLinkInNewWindow': 'Open the results in a new window',
            'CaseCreation_NoResults': 'No results',
            'CaseCreationInterface_enableAutomaticResponsiveMode': 'Enable automatic responsive mode',
            'CaseCreationInterface_maximumAge': 'Maximum age',
            'CaseCreationQuerySummary_messageOnNoResult': 'Message on no results',
            'CaseCreationQuerySummary_messageOnNoResult_description': 'Message to display when no results are found.',
            'Field_title': 'Title',
            'Field_title_description': 'Specifies the title to display above the input.',
            'Field_caseField': 'Case field',
            'Field_caseField_description': 'Specifies the field in which to save the input value when the end-user submits the form.',
            'Field_numberOfLines': 'Number of lines',
            'Field_numberOfLines_description': 'Specifies the input height in number of lines.',
            'Field_placeholder': 'Placeholder',
            'Field_placeholder_description': 'Specifies a short hint displayed inside the input before the end-user enters a value.',
            'Field_tooltip': 'Tooltip',
            'Field_tooltip_description': 'Specifies what to display when the end-user\'s mouse is over the title.',
            'Field_isRequired': 'Is required',
            'Field_isRequired_description': 'Specifies whether the input has to be filled before the form can be submitted.',
            'Field_enableSearch': 'Include in search',
            'Field_enableSearch_description': 'Specifies whether to include the entered keywords in the query.',
            'Field_addQre': 'Add QRE',
            'Field_addQre_description': 'Specifies whether to add a query ranking expression (QRE) in the search query using the input value as the expression.',
            'Field_queryModifier': 'Query modifier',
            'Field_queryModifier_description': 'Specifies how to affect the ranking score for documents containing the entered keywords.',
            'Field_addSome': 'Add "some"',
            'Field_addSome_description': 'Specifies whether to add a $some query extension in the query.',
            'Field_someBest': 'Best',
            'Field_someBest_description': 'Specifies the X best keywords that are to be matched.',
            'Field_someMatch': 'Match',
            'Field_someMatch_description': 'Specifies that only documents containing X or more keywords of those provided are to be matched.',
            'Field_someRemoveStopWords': 'Remove stop words',
            'Field_someRemoveStopWords_description': 'Specifies whether to remove any stop word present in the keywords.',
            'Field_someMaximum': 'Maximum',
            'Field_someMaximum_description': 'Specifies the maximum number of keywords to use. If more keywords are provided, some keywords are completely ignored.',
            'Field_addCorrelateUsingIdf': 'Add correlateUsingIdf',
            'Field_addCorrelateUsingIdf_description': 'Specifies whether to add a $correlateUsingIdf query extension to the search query.',
            'Field_correlateForceOneMatch': 'Force one match',
            'Field_correlateForceOneMatch_description': 'Specifies whether to ensure that all results have at least one matching keyword.',
            'Field_correlateRemoveStopWords': 'Remove stop words',
            'Field_correlateRemoveStopWords_description': 'Specifies whether to remove any stop word present in the keywords.',
            'Field_correlateNoStemming': 'No stemming',
            'Field_correlateNoStemming_description': 'If true, keywords are not expanded using the index stemming before matching documents.',
            'Field_correlateMaximum': 'Maximum',
            'Field_correlateMaximum_description': 'Specifies the maximum number of keywords to use. If more keywords are provided, some keywords are completely ignored.',
            'Picklist_title': 'Title',
            'Picklist_title_description': 'Specifies the title to display above the picklist.',
            'Picklist_caseField': 'Case field',
            'Picklist_caseField_description': 'Specifies the field in which to save the picklist value when the end-user submits the form.',
            'Picklist_values': 'Values',
            'Picklist_values_description': 'Specifies the values available in the picklist. If this option is left empty, they will be automatically obtained using the caseField option.',
            'Picklist_defaultValue': 'Default value',
            'Picklist_defaultValue_description': 'Specifies the default selected value of the picklist.',
            'Picklist_placeholder': 'Placeholder',
            'Picklist_placeholder_description': 'Specifies the text to display when no option is selected.',
            'Picklist_tooltip': 'Tooltip',
            'Picklist_tooltip_description': 'Specifies what to display when the end-user\'s mouse is over the title.',
            'Picklist_isRequired': 'Is required',
            'Picklist_isRequired_description': 'Specifies whether an option in this picklist has to be selected before the form can be submitted.',
            'Picklist_enableSearch': 'Enable search',
            'Picklist_enableSearch_description': 'Specifies whether to include the selected option keywords in the search for related case.',
            'Picklist_addQre': 'Add QRE',
            'Picklist_addQre_description': 'Specifies whether to add a query ranking expression (QRE) in the query using the searchField and the selected option as expression.',
            'Picklist_searchField': 'Search field',
            'Picklist_searchField_description': 'Specifies the field to use in the query ranking expression (QRE) added to the search query.',
            'Picklist_queryModifier': 'Query modifier',
            'Picklist_queryModifier_description': 'Specifies how to affect the ranking score for documents where the searchField is equal to the selected option.',
            'Picklist_addSome': 'Add Some',
            'Picklist_addSome_description': 'Specifies whether to add a $some query extensions in the query.',
            'Picklist_someBest': 'Best',
            'Picklist_someBest_description': 'Specifies the X best keywords that are to be matched.',
            'Picklist_someMatch': 'Match',
            'Picklist_someMatch_description': 'Specifies that only documents containing X or more keywords of those provided are to be matched.',
            'Picklist_someRemoveStopWords': 'Remove stop words',
            'Picklist_someRemoveStopWords_description': 'Specifies whether to remove any stop word present in the keywords.',
            'Picklist_someMaximum': 'Maximum',
            'Picklist_someMaximum_description': 'Specifies the maximum number of keywords to use. If more keywords are provided, some keywords are completely ignored.',
            'Picklist_addCorrelateUsingIdf': 'Add correlateUsingIdf',
            'Picklist_addCorrelateUsingIdf_description': 'Specifies whether to add a $correlateUsingIdf query extensions to the search query.',
            'Picklist_correlateForceOneMatch': 'Force one match',
            'Picklist_correlateForceOneMatch_description': 'Specifies whether to ensure that all results have at least one matching keyword.',
            'Picklist_correlateRemoveStopWords': 'Remove stop words',
            'Picklist_correlateRemoveStopWords_description': 'Specifies whether to remove any stop word present in the keywords.',
            'Picklist_correlateNoStemming': 'No stemming',
            'Picklist_correlateNoStemming_description': 'If true, keywords are not expanded using the index stemming before matching documents.',
            'Picklist_correlateMaximum': 'Maximum',
            'Picklist_correlateMaximum_description': 'Specifies the maximum number of keywords to use. If more keywords are provided, some keywords are completely ignored.',
            'Submit_title': 'Title',
            'Submit_title_description': 'Specifies the text to display on the button.',
            'Submit_redirectUrl': 'Redirect URL',
            'Submit_redirectUrl_description': 'Specifies where to redirect the end-user once the case has been submitted.',
            'Cancel_title': 'Title',
            'Cancel_title_description': 'Specifies the text to display on the button.',
            'Cancel_redirectUrl': 'Redirect URL',
            'Cancel_redirectUrl_description': 'Specifies where to redirect the end-user once the case has been canceled.'
        }
    });
}
